//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ткани
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
        }
        TradeEntities entity = new TradeEntities();
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public int ProductCategory { get; set; }
        public string Category
        {
            get
            {
                var category = entity.ProductCategories.First(x => x.ID == ProductCategory);
                return category.Name;
            }
        }
        public byte[] ProductPhoto { get; set; }
        public int ProductManufacturer { get; set; }
        public string Manufacturer
        {
            get
            {
                var manufacturer = entity.ProductManufactures.First(x => x.ID == ProductManufacturer);
                return manufacturer.Name;
            }
        }
        public decimal ProductCost { get; set; }
        public byte ProductDiscountAmountMax { get; set; }
        public int ProductQuantityInStock { get; set; }
        public int ProductSupplier { get; set; }
        public string Supplier
        {
            get
            {
                var supplier = entity.ProductSuppliers.First(x => x.ID == ProductSupplier);
                return supplier.Name;
            }
        }
        public int ProductMeasure { get; set; }
        public string Measure
        {
            get
            {
                var measure = entity.ProductMeasures.First(x => x.ID == ProductMeasure);
                return measure.Name;
            }
        }
        public byte ProductRealDiscountAmount { get; set; }
    
        public virtual ProductCategories ProductCategories { get; set; }
        public virtual ProductManufactures ProductManufactures { get; set; }
        public virtual ProductMeasures ProductMeasures { get; set; }
        public virtual ProductSuppliers ProductSuppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
